use serde::{Deserialize, Serialize};
use tracing::{error, info};

/// Notification channels supported by the platform
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NotificationChannel {
    Email,
    Webhook,
    Slack,
}

/// A notification to be sent
#[derive(Debug, Clone, Serialize)]
pub struct Notification {
    pub channel: NotificationChannel,
    pub subject: String,
    pub body: String,
    pub severity: String,
    pub metadata: serde_json::Value,
}

/// Configuration for notification dispatch
#[derive(Debug, Clone, Deserialize)]
pub struct NotificationConfig {
    pub smtp_host: String,
    pub smtp_port: u16,
    pub smtp_username: String,
    pub smtp_password: String,
    pub from_email: String,
    pub to_emails: Vec<String>,
    pub webhook_urls: Vec<String>,
    pub slack_webhook_url: Option<String>,
    pub enabled_channels: Vec<NotificationChannel>,
    pub min_severity: String,
}

impl Default for NotificationConfig {
    fn default() -> Self {
        Self {
            smtp_host: "smtp.gmail.com".to_string(),
            smtp_port: 587,
            smtp_username: String::new(),
            smtp_password: String::new(),
            from_email: "dummymailrangga@gmail.com".to_string(),
            to_emails: vec!["dummymailrangga@gmail.com".to_string()],
            webhook_urls: Vec::new(),
            slack_webhook_url: None,
            enabled_channels: vec![NotificationChannel::Email],
            min_severity: "high".to_string(),
        }
    }
}

/// Notification dispatcher
#[derive(Clone)]
pub struct NotificationDispatcher {
    config: NotificationConfig,
    http_client: reqwest::Client,
}

impl NotificationDispatcher {
    pub fn new(config: NotificationConfig) -> Self {
        Self {
            config,
            http_client: reqwest::Client::new(),
        }
    }

    /// Send a notification through all enabled channels
    pub async fn dispatch(&self, notification: &Notification) {
        if !self.should_notify(&notification.severity) {
            return;
        }

        for channel in &self.config.enabled_channels {
            match channel {
                NotificationChannel::Email => {
                    if let Err(e) = self.send_email(notification).await {
                        error!("Failed to send email notification: {e}");
                    }
                }
                NotificationChannel::Webhook => {
                    if let Err(e) = self.send_webhook(notification).await {
                        error!("Failed to send webhook notification: {e}");
                    }
                }
                NotificationChannel::Slack => {
                    if let Err(e) = self.send_slack(notification).await {
                        error!("Failed to send Slack notification: {e}");
                    }
                }
            }
        }
    }

    fn should_notify(&self, severity: &str) -> bool {
        let levels = ["low", "medium", "high", "critical"];
        let min_idx = levels.iter().position(|&s| s == self.config.min_severity).unwrap_or(0);
        let sev_idx = levels.iter().position(|&s| s == severity).unwrap_or(0);
        sev_idx >= min_idx
    }

impl NotificationDispatcher {
    /// Send email notification via SMTP
    async fn send_email(&self, notification: &Notification) -> anyhow::Result<()> {
        let html_body = format!(
            r#"<html><body>
<h2>🔱 Raksha Security Alert</h2>
<div style="border-left:4px solid {};padding:16px;background:#f8f9fa">
<p style="font-weight:bold;text-transform:uppercase;color:{}">{} Severity</p>
<h3>{}</h3><p>{}</p></div>
<p style="color:#6c757d;font-size:12px;margin-top:24px">
Generated by <a href="https://github.com/dansiapa/raksha-security-platform">Raksha Security Platform</a>
</p></body></html>"#,
            self.severity_color(&notification.severity),
            self.severity_color(&notification.severity),
            notification.severity,
            notification.subject,
            notification.body,
        );

        for to_email in &self.config.to_emails {
            let email = lettre::Message::builder()
                .from(self.config.from_email.parse()?)
                .to(to_email.parse()?)
                .subject(format!(
                    "[Raksha][{}] {}",
                    notification.severity.to_uppercase(),
                    notification.subject
                ))
                .header(lettre::message::header::ContentType::TEXT_HTML)
                .body(html_body.clone())?;

            let creds = lettre::transport::smtp::authentication::Credentials::new(
                self.config.smtp_username.clone(),
                self.config.smtp_password.clone(),
            );

            let mailer = lettre::AsyncSmtpTransport::<lettre::Tokio1Executor>::starttls_relay(
                &self.config.smtp_host,
            )?
            .port(self.config.smtp_port)
            .credentials(creds)
            .build();

            lettre::AsyncTransport::send(&mailer, email).await?;
            info!("Email notification sent to {to_email}");
        }
        Ok(())
    }

    /// Send webhook notification (generic HTTP POST)
    async fn send_webhook(&self, notification: &Notification) -> anyhow::Result<()> {
        let payload = serde_json::json!({
            "event": "security_alert",
            "severity": notification.severity,
            "subject": notification.subject,
            "body": notification.body,
            "metadata": notification.metadata,
            "timestamp": chrono::Utc::now().to_rfc3339(),
            "source": "raksha-security-platform",
        });

        for url in &self.config.webhook_urls {
            let resp = self.http_client
                .post(url)
                .json(&payload)
                .header("User-Agent", "Raksha-Security-Platform/0.1")
                .header("X-Raksha-Event", "security_alert")
                .send()
                .await?;

            if resp.status().is_success() {
                info!("Webhook notification sent to {url}");
            } else {
                error!("Webhook returned {}: {url}", resp.status());
            }
        }
        Ok(())
    }

    /// Send Slack notification
    async fn send_slack(&self, notification: &Notification) -> anyhow::Result<()> {
        let url = match &self.config.slack_webhook_url {
            Some(u) => u,
            None => return Ok(()),
        };

        let emoji = match notification.severity.as_str() {
            "critical" => "🚨",
            "high" => "⚠️",
            "medium" => "🔶",
            _ => "ℹ️",
        };

        let payload = serde_json::json!({
            "blocks": [
                {
                    "type": "header",
                    "text": { "type": "plain_text", "text": format!("{emoji} Raksha Security Alert") }
                },
                {
                    "type": "section",
                    "fields": [
                        { "type": "mrkdwn", "text": format!("*Severity:*\n{}", notification.severity) },
                        { "type": "mrkdwn", "text": "*Source:*\nRaksha Platform" },
                    ]
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": format!("*{}*\n{}", notification.subject, notification.body)
                    }
                }
            ]
        });

        self.http_client.post(url).json(&payload).send().await?;
        info!("Slack notification sent");
        Ok(())
    }
}


    fn severity_color(&self, severity: &str) -> &'static str {
        match severity {
            "critical" => "#dc3545",
            "high" => "#fd7e14",
            "medium" => "#ffc107",
            _ => "#28a745",
        }
    }
}
