pub mod server;
pub mod network;
pub mod process;
pub mod filesystem;

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

/// A collected metric data point.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MetricPayload {
    pub agent_id: String,
    pub hostname: String,
    pub timestamp: DateTime<Utc>,
    pub category: MetricCategory,
    pub data: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MetricCategory {
    Server,
    Network,
    Process,
    FileIntegrity,
}

/// Alert severity levels.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AlertSeverity {
    Low,
    Medium,
    High,
    Critical,
}

/// An alert generated by the agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Alert {
    pub agent_id: String,
    pub hostname: String,
    pub timestamp: DateTime<Utc>,
    pub severity: AlertSeverity,
    pub category: MetricCategory,
    pub title: String,
    pub description: String,
    pub metadata: serde_json::Value,
}
