{{- $fullName := include "raksha.fullname" . -}}
{{- $labels := include "raksha.labels" . -}}
{{- if .Values.persistence.data.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-data
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
{{- if .Values.persistence.models.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-models
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: ml-engine
spec:
  accessModes:
    - {{ .Values.persistence.models.accessMode }}
  storageClassName: {{ .Values.persistence.models.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.models.size }}
{{- end }}
{{- if .Values.persistence.logs.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-logs
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: logging
spec:
  accessModes:
    - {{ .Values.persistence.logs.accessMode }}
  storageClassName: {{ .Values.persistence.logs.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
{{- end }}
