{{- $fullName := include "raksha.fullname" . -}}
{{- $labels := include "raksha.labels" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-portal
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: portal
spec:
  type: {{ .Values.portal.service.type }}
  ports:
    - port: {{ .Values.portal.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "raksha.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: portal
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-web
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "raksha.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-ml
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: ml-engine
spec:
  type: {{ .Values.ml.service.type }}
  ports:
    - port: {{ .Values.ml.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "raksha.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ml-engine
---
{{- if .Values.admissionWebhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-webhook
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
spec:
  type: {{ .Values.admissionWebhook.service.type }}
  ports:
    - port: {{ .Values.admissionWebhook.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "raksha.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: admission-webhook
{{- end }}
