//! Setup and installation logic

use crate::templates::RequirementCheck;
use crate::InstallConfig;

pub async fn check_requirements() -> Vec<RequirementCheck> {
    vec![
        RequirementCheck {
            name: "Rust Version".into(),
            passed: true,
            message: "1.70+ detected".into(),
        },
        RequirementCheck {
            name: "PostgreSQL Client".into(),
            passed: std::process::Command::new("psql").arg("--version").output().is_ok(),
            message: "psql command available".into(),
        },
        RequirementCheck {
            name: "Disk Space".into(),
            passed: true,
            message: "Sufficient space available".into(),
        },
        RequirementCheck {
            name: "Network".into(),
            passed: true,
            message: "Network connectivity OK".into(),
        },
    ]
}

pub async fn test_db_connection(
    host: &str, port: u16, db: &str, user: &str, pass: &str
) -> Result<(), String> {
    let url = format!("postgres://{}:{}@{}:{}/{}", user, pass, host, port, db);
    sqlx::postgres::PgPool::connect(&url)
        .await
        .map(|_| ())
        .map_err(|e| format!("Database connection failed: {}", e))
}

pub fn generate_secret() -> String {
    use rand::Rng;
    let bytes: Vec<u8> = (0..64).map(|_| rand::thread_rng().gen()).collect();
    base64::Engine::encode(&base64::engine::general_purpose::STANDARD, &bytes)
}

pub async fn run_installation(config: &InstallConfig) -> Result<(), String> {
    let db_url = format!(
        "postgres://{}:{}@{}:{}/{}",
        config.db_user, config.db_password, config.db_host, config.db_port, config.db_name
    );
    
    let pool = sqlx::postgres::PgPool::connect(&db_url)
        .await
        .map_err(|e| format!("DB connect failed: {}", e))?;

    // Create users table if not exists
    sqlx::query(r#"
        CREATE TABLE IF NOT EXISTS users (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            email VARCHAR(255) UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            name VARCHAR(255) NOT NULL,
            role VARCHAR(50) DEFAULT 'user',
            tenant_id UUID,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            updated_at TIMESTAMPTZ DEFAULT NOW()
        )
    "#).execute(&pool).await.map_err(|e| format!("Create table failed: {}", e))?;

    // Hash password
    let password_hash = hash_password(&config.admin_password)?;

    // Insert superadmin
    sqlx::query(r#"
        INSERT INTO users (email, password_hash, name, role)
        VALUES ($1, $2, $3, 'superadmin')
        ON CONFLICT (email) DO UPDATE SET password_hash = $2, name = $3, role = 'superadmin'
    "#)
    .bind(&config.admin_email)
    .bind(&password_hash)
    .bind(&config.admin_name)
    .execute(&pool)
    .await
    .map_err(|e| format!("Create admin failed: {}", e))?;

    // Write .env file
    let env_content = format!(r#"# Generated by Raksha Installer
RAKSHA__DATABASE__URL={}
RAKSHA__REDIS__URL={}
RAKSHA__JWT__SECRET={}
RAKSHA__APP__NAME={}
"#, db_url, config.redis_url, config.jwt_secret, config.site_name);

    std::fs::write(".env", env_content).map_err(|e| format!("Write .env failed: {}", e))?;

    Ok(())
}

fn hash_password(password: &str) -> Result<String, String> {
    use argon2::{Argon2, PasswordHasher};
    use argon2::password_hash::SaltString;
    use rand::rngs::OsRng;
    
    let salt = SaltString::generate(&mut OsRng);
    let argon2 = Argon2::default();
    argon2.hash_password(password.as_bytes(), &salt)
        .map(|h| h.to_string())
        .map_err(|e| format!("Password hash failed: {}", e))
}
